create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_profile_id uuid not null references public.profiles(id) on delete cascade,
  target_type text not null,
  target_event_id bigint references public.events(id) on delete cascade,
  target_profile_id uuid references public.profiles(id) on delete cascade,
  reason text not null,
  details text,
  created_at timestamptz not null default now(),
  constraint reports_target_type_check
    check (target_type in ('event', 'profile')),
  constraint reports_reason_check
    check (nullif(trim(reason), '') is not null),
  constraint reports_single_target_check
    check (
      (case when target_event_id is null then 0 else 1 end) +
      (case when target_profile_id is null then 0 else 1 end) = 1
    )
);

create index if not exists reports_reporter_created_at_idx
on public.reports(reporter_profile_id, created_at desc);

create index if not exists reports_target_event_idx
on public.reports(target_event_id)
where target_event_id is not null;

create index if not exists reports_target_profile_idx
on public.reports(target_profile_id)
where target_profile_id is not null;

alter table public.reports enable row level security;

drop policy if exists "Users can create reports" on public.reports;
create policy "Users can create reports"
on public.reports
for insert
to authenticated
with check (auth.uid() = reporter_profile_id);

drop policy if exists "Users can read their own reports" on public.reports;
create policy "Users can read their own reports"
on public.reports
for select
to authenticated
using (auth.uid() = reporter_profile_id);
