alter table public.comments
add column if not exists parent_comment_id bigint references public.comments(id) on delete cascade;

create index if not exists comments_parent_comment_id_idx
on public.comments(parent_comment_id);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_profile_id uuid not null references public.profiles(id) on delete cascade,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  type text not null,
  title text not null,
  body text not null,
  dedupe_key text not null unique,
  event_id bigint references public.events(id) on delete cascade,
  comment_id bigint references public.comments(id) on delete cascade,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_recipient_profile_id_created_at_idx
on public.notifications(recipient_profile_id, created_at desc);

create index if not exists notifications_recipient_profile_id_read_at_idx
on public.notifications(recipient_profile_id, read_at);

alter table public.notifications enable row level security;

drop policy if exists "Users can read their notifications" on public.notifications;
create policy "Users can read their notifications"
on public.notifications
for select
to authenticated
using (auth.uid() = recipient_profile_id);

drop policy if exists "Users can update their notifications" on public.notifications;
create policy "Users can update their notifications"
on public.notifications
for update
to authenticated
using (auth.uid() = recipient_profile_id)
with check (auth.uid() = recipient_profile_id);

drop policy if exists "Authenticated users can insert notifications" on public.notifications;
create policy "Authenticated users can insert notifications"
on public.notifications
for insert
to authenticated
with check (auth.uid() is not null);
